# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastlite_improve_dataclass_automatic_name',
                'doc_host': 'https://ozpau.github.io',
                'git_url': 'https://github.com/ozpau/fastlite_improve_dataclass_automatic_name',
                'lib_path': 'fastlite_improve_dataclass_automatic_name'},
  'syms': { 'fastlite_improve_dataclass_automatic_name.core': { 'fastlite_improve_dataclass_automatic_name.core.foo': ( 'core.html#foo',
                                                                                                                        'fastlite_improve_dataclass_automatic_name/core.py')}}}
